/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    'tour-operadora': TourOperadora;
    paginas: Pagina;
    users: User;
    media: Media;
  };
  globals: {};
}
export interface TourOperadora {
  id: string;
  nombre: string;
  urlWeb: string;
  descripcion: string;
  imagenesDePresentacion: {
    imagen: string | Media;
    id?: string;
  }[];
  conMapaDeUbicacion?: boolean;
  iframeDeLaUbicacion: string;
  galeria: {
    imagen: string | Media;
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface Media {
  id: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes: {
    thumbnail: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    card: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    tablet: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
  createdAt: string;
  updatedAt: string;
}
export interface Pagina {
  id: string;
  titulo: string;
  secciones: (
    | {
        content: string;
        contenido: string;
        nesecitaUrl?: boolean;
        url: string;
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        titulo: string;
        contenido: string;
        imagen: string | Media;
        nesecitaUrl?: boolean;
        url: string;
        id?: string;
        blockName?: string;
        blockType: 'content-with-image';
      }
    | {
        titulo: string;
        puntos: {
          numero: number;
          contenido: string;
          ilustracion: string | Media;
          id?: string;
        }[];
        nesecitaUrl?: boolean;
        url: string;
        id?: string;
        blockName?: string;
        blockType: 'list-content';
      }
  )[];
  autor?: string | User;
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface User {
  id: string;
  nombre: string;
  apellidos: string;
  photo?: string | Media;
  roles: ('admin' | 'public' | 'editor')[];
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
